// PSP Dashboard - Data Automation Tool for PSP-like processes
// Copyright (C) 1999  United States Air Force
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
// The author(s) may be contacted at:
// OO-ALC/TISHD
// Attn: PSP Dashboard Group
// 6137 Wardleigh Road
// Hill AFB, UT 84056-5843
//
// E-Mail POC:  ken.raisor@hill.af.mil

package net.sourceforge.processdash.tool.probe;


import java.io.PrintWriter;

import pspdash.StringUtils;


class MethodD extends Method {

    double estimate;
    boolean isOnly = false;

    /** Perform the calculations required for this PROBE Method. */
    public MethodD(HistData data, double estimate, String purpose) {
        super(data, 0, "D", purpose);
        this.estimate = estimate;
    }


    public double getRating() { return PROBE_METHOD_D; }
    public void setIsOnly(boolean i) { isOnly = i; }


    public void printRow(PrintWriter out, boolean isBest, boolean isSelected) {
        out.print("<tr><td valign=middle>");

        printOption(out, isSelected);

        out.print("</td><td valign=middle>&nbsp;<br>");

        String estTarget = ("size".equals(getMethodPurpose()) ?
                            "new and changed LOC" : "total development time");
        String link = ("<a "+ProbeWizard.LINK_ATTRS+" href='"+getMethodPurpose()+
                       "Dtut.htm'>");
        if (isOnly)
            out.println
                ("Use your engineering judgement to estimate the "+estTarget+
                 " from the estimated object LOC, and enter it in the field "+
                 "to the left.");
        else if (isBest)
            out.println
                ("Your best option for estimating " + getMethodPurpose() +
                 " could be "+link+"PROBE method D</a>. Use your engineering "+
                 "judgement to estimate the "+estTarget+" from the estimated "+
                 "object LOC, and enter it in the field to the left.");
        else
            out.println
                ("Your next best option is probably "+link+"PROBE method "+
                 "D</a>. Use your engineering judgement to examine the "+
                 "estimates generated by the other PROBE methods.  If you do "+
                 "not feel that they accurately project the " + estTarget +
                 " required for this project, then make your best estimate "+
                 "of the " + estTarget + " and enter it in the field "+
                 "to the left.");

        out.print("<br>&nbsp;</td><td valign=middle>");
        out.print(NBSP);
        out.print("</td></tr>");
    }

    void printOption(PrintWriter out, boolean isSelected) {
        String purpose = getMethodPurpose();
        String letter = getMethodLetter();
        String qual = purpose + letter;

        out.print("<input ");
        if (isOnly)
            out.print("type='hidden' ");
        else {
            out.print("type='radio' ");
            if (isSelected) out.print("checked ");
        }
        out.print("name='" + purpose + "' ");
        out.print("value='" + letter + "'>");
        out.print("<input type='text' name='"+ qual+FLD_ESTIMATE +"' value='");
        if (Double.isNaN(estimate))
            out.print("?????");
        else
            out.print(formatNumber(estimate));
        out.print("' size='7'");
        if (!isOnly)
            out.print(" onFocus='select_"+purpose+"D();'");
        out.print("><tt>" + NBSP);
        out.print(("size".equals(purpose)) ? "LOC" : "Hours");
        out.print(NBSP + NBSP + NBSP + "</tt>\n");
        if (!isOnly)
            out.print(StringUtils.findAndReplace(SCRIPT, "PURPOSE", purpose));
        printField(out, FLD_BETA0, qual, -1);
        printField(out, FLD_BETA1, qual, -1);
        printField(out, FLD_RANGE, qual, -1);
        printField(out, FLD_PERCENT, qual, -1);
        printField(out, FLD_CORRELATION, qual, -1);
    }
    private static final String SCRIPT =
        "<script>\n"+
        "    var PURPOSEDoption = document.forms[0].PURPOSE.length - 1;\n"+
        "    if (!(PURPOSEDoption > -1)) PURPOSEDoption = 0;\n"+
        "    function select_PURPOSED() {\n"+
        "      if (document.forms[0].PURPOSE[PURPOSEDoption])\n"+
        "        document.forms[0].PURPOSE[PURPOSEDoption].checked = true;\n"+
        "    }\n"+
        "</script>\n";

    void printTableRow(PrintWriter out, boolean isSelected) {
        if (isSelected)
            printTableRow(out, estimate, isSelected, Double.NaN,
                          Double.NaN, Double.NaN, Double.NaN, Double.NaN);
    }
}
