// PSP Dashboard - Data Automation Tool for PSP-like processes
// Copyright (C) 1999  United States Air Force
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
// The author(s) may be contacted at:
// OO-ALC/TISHD
// Attn: PSP Dashboard Group
// 6137 Wardleigh Road
// Hill AFB, UT 84056-5843
//
// E-Mail POC:  ken.raisor@hill.af.mil

import java.io.PrintWriter;
import java.util.Iterator;
import java.util.Vector;

import pspdash.StringUtils;
import pspdash.data.DoubleData;

class MethodD extends Method {

    /** Perform the calculations required for this PROBE Method. */
    public MethodD(HistData data, double estObjLOC, String purpose) {
        super(data, estObjLOC, "D", purpose);
    }


    public double getRating() { return PROBE_METHOD_D; }


    public void printRow(PrintWriter out, boolean isBest) {
        out.print("<tr><td valign=middle>");

        printOption(out, isBest);

        out.print("</td><td valign=middle>&nbsp;<br>");

        String estTarget = ("size".equals(getMethodPurpose()) ?
                            "new and changed LOC" : "total development time");
        if (isBest)
            out.println
                ("Your best option for estimating " + getMethodPurpose() +
                 " could be PROBE method D. Use your engineering judgement "+
                 "to estimate the " + estTarget + " from the estimated "+
                 "object LOC, and enter it in the field to the left.");
        else
            out.println
                ("Your next best option is probably PROBE method D. " +
                 "Use your engineering judgement to examine the estimates "+
                 "generated by the other PROBE methods.  If you do not feel "+
                 "that they accurately project the " + estTarget +
                 " required for this project, then make your best estimate "+
                 "of the " + estTarget + " and enter it in the field "+
                 "to the left.");

        out.print("<br>&nbsp;</td><td valign=middle>");
        out.print(NBSP);
        out.print("</td></tr>");
    }

    void printOption(PrintWriter out, boolean isBest) {
        String purpose = getMethodPurpose();
        String letter = getMethodLetter();
        String qual = purpose + letter;

        out.print("<input type='radio' ");
        if (isBest) out.print("checked ");
        out.print("name='" + purpose + "' ");
        out.print("value='" + letter + "'>");
        out.print("<input type='text' name='"+ qual+FLD_ESTIMATE +"' value='");
        if ("size".equals(purpose))
            out.print(formatNumber(estObjLOC));
        else
            out.print("?????");
        out.print("' size='7' onFocus='select_"+purpose+"D();'><tt>" + NBSP);
        out.print(("size".equals(purpose)) ? "LOC" : "Hours");
        out.print(NBSP + NBSP + NBSP + "</tt>\n");
        out.print(StringUtils.findAndReplace(SCRIPT, "PURPOSE", purpose));
        printField(out, FLD_BETA0, qual, -1);
        printField(out, FLD_BETA1, qual, -1);
        printField(out, FLD_RANGE, qual, -1);
        printField(out, FLD_PERCENT, qual, -1);
        printField(out, FLD_CORRELATION, qual, -1);
    }
    private static final String SCRIPT =
        "<script>\n"+
        "    var PURPOSEDoption = document.forms[0].PURPOSE.length - 1;\n"+
        "    function select_PURPOSED() {\n"+
        "        document.forms[0].PURPOSE[PURPOSEDoption].checked = true;\n"+
        "    }\n"+
        "</script>\n";
}
