###
### Application defaults for the Database Synchronizer
###

# by default, pull the item ID from the first column of the query
itemIdIdx=1

# by default, the human-readable key is the same as the ID
itemKeyFmt={${itemIdIdx}}

# by default, pull the simple name from the second column of the query
itemSimpleNameFmt={2}

# create the default WBS name by appending the key and the simple name
itemNameFmt=#${itemKeyFmt} ${itemSimpleNameFmt}

# if no item type is provided, use "Item" as a default
itemTypeFmt=Item

#if no item type ID is configured, use the type redundantly
itemTypeIdFmt=${itemTypeFmt}

# provide a default template for hyperlink text
itemUrlTextFmt=${systemName} ${itemTypeFmt} #${itemKeyFmt}

# create components in the WBS for incoming items
wbsNodeType=Component
