#!/usr/afms02/gnu/bin/perl

#############################################################################
## PSP Dashboard - Data Automation Tool for PSP-like processes
## Copyright (C) 1999  United States Air Force
## 
## This program is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License
## as published by the Free Software Foundation; either version 2
## of the License, or (at your option) any later version.
## 
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
## 
## You should have received a copy of the GNU General Public License
## along with this program; if not, write to the Free Software
## Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
## 
## The author(s) may be contacted at:
## OO-ALC/TISHD
## Attn: PSP Dashboard Group
## 6137 Wardleigh Road
## Hill AFB, UT 84056-5843
## 
## E-Mail POC:  ken.raisor@hill.af.mil


$NETSCAPE_DIR = "/usr/afms02/netscape";


# parse command line arg.
$url = pop if (@ARGV);

# clobber the CLASSPATH.
$ENV{'CLASSPATH'}='';

# cd to the netscape directory.
chdir($NETSCAPE_DIR);

# get list of currently running processes.
$ps_out = `ps -ef`;



if ($ps_out =~ m:$NETSCAPE_DIR/netscape:) {

    # Netscape is already running.

    if ($url) {
	exec "$NETSCAPE_DIR/netscape", "-noraise", "-remote", "openURL($url, window$$)";
    } else {
	exec "$NETSCAPE_DIR/netscape", "-noraise", "-remote", "openURL(about:, window$$)";
    }

} else {

    # we need to kick off Netscape.

    unlink("$ENV{HOME}/.netscape/lock");

    if ($url) { exec "$NETSCAPE_DIR/netscape", "-ncols", "32", $url }
    else      { exec "$NETSCAPE_DIR/netscape", "-ncols", "32" }

}
