/* Generated By:JavaCC: Do not edit this line. UtfParserConstants.java */
package org.zaval.tools.i18n.translator;

public interface UtfParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 7;
  int KEY = 9;
  int EQ = 10;
  int DBC = 11;
  int STRING_LITERAL_1 = 12;
  int STRING_LITERAL_2 = 13;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"\\n\"",
    "\"#\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 8>",
    "\"KEY\"",
    "\"=\"",
    "\":\"",
    "<STRING_LITERAL_1>",
    "<STRING_LITERAL_2>",
  };

}
